class ValidationPipeline:
    """Pipeline for validating code files generated by the LLM"""
  
    def __init__(self, output_dir: str):
    	"""
		Initialize the pipeline.
	
		Args:
			output_dir: directory to write output files to for various tools
				(this means captured `stdout` and `stderr` streams)
        """
		self.output_dir = output_dir
		self.compilation = CompilationStage(output_dir)
		self.static_analysis = StaticAnalysisStage(output_dir)
		# To be implemented in future sprints
		# ====================================
		# self.dynamic_analysis = DynamicAnalysisStage(output_dir)
		# self.style_analysis = StyleAnalysisStage(output_dir)
		# self.unit_tester = UnitTestStage(output_dir)

	def run(self) -> Dict[str, str]:
		"""
		Run the pipeline

		Returns:
			A dictionary mapping the name of validation stage to collection of output
		"""
		results = {}
		results["compilation"] = self.compilation.run()
		results["static_analysis"] = self.static_analysis.run()
		# Further steps to be implemented later...
		return results